<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Student::insert([
            [
                'name' => 'Ahmad Bukhari',
                'nisn' => '0083673687',
                'tgl_lahir' => '2008-01-21',
                'tlp' => '6281774962905',
                'jk' => 'L',
                'address' => 'Pondok Ungu , MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17132',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ahmad Fariz',
                'nisn' => '0085600699',
                'tgl_lahir' => '2008-04-05',
                'tlp' => '62895612290304',
                'jk' => 'L',
                'address' => 'Jl. Raya Seroja Al Bahar RT 005/018 No. 34 Harapan Jaya Bekasi Utara , BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ahmad Gifahri',
                'nisn' => '3081673835',
                'tgl_lahir' => '2008-03-02',
                'tlp' => '628981154339',
                'jk' => 'L',
                'address' => 'Pondok Ungu Rt 002/07 , MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17132',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amaruddin',
                'nisn' => '3072478152',
                'tgl_lahir' => '2007-12-11',
                'tlp' => '62898973740946',
                'jk' => 'L',
                'address' => 'KALIABANG BUNGUR HARAPANJAYA, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arrya Ainun Nazib',
                'nisn' => '3071703615',
                'tgl_lahir' => '2007-10-31',
                'tlp' => '6281297736269',
                'jk' => 'P',
                'address' => 'KP CEGER RT 006/002 HARAPANJAYA, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aulia Zahra Muharromi',
                'nisn' => '0084314531',
                'tgl_lahir' => '2008-02-02',
                'tlp' => null,
                'jk' => 'P',
                'address' => 'Jalan Gang Putri 2 Seroja, RT 2/RW 28,No 36, Harapan Jaya,Kota Bekasi, Bekasi Utara, Jawa Barat,17124 HARAPANJAYA, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Balqis Hamima Azwa',
                'nisn' => '0089808534',
                'tgl_lahir' => '2008-01-11',
                'tlp' => null,
                'jk' => 'P',
                'address' => 'PERUM PEJUANG JAYA, JL. CENDRAWASIH 7 BLOK F NO. 75 RT.2/RW.13 PEJUANG, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17131, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dela Retna Asih Ardiliani',
                'nisn' => '3089003352',
                'tgl_lahir' => '2007-07-26',
                'tlp' => '628989516944204',
                'jk' => 'P',
                'address' => 'KALIABANG BUNGUR PEJUANG, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17131, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dewi Siti Syarifah',
                'nisn' => '3070550144',
                'tgl_lahir' => '2007-08-06',
                'tlp' => '6287782422270',
                'jk' => 'P',
                'address' => 'KA DUKUH PEJUANG, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17131, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gadiza Azkarani',
                'nisn' => '0073747715',
                'tgl_lahir' => '2007-10-20',
                'tlp' => null,
                'jk' => 'P',
                'address' => 'Jl.satria Raya RT 010 RW 02 Ujung Menteng Cakung Jakarta Timur UJUNG MENTENG, CAKUNG, KOTA ADM. JAKARTA TIMUR, DAERAH KHUSUS IBUKOTA JAKARTA, 13960, 13960',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Galfin Gastiadirrijal Ibrahim',
                'nisn' => '0087377301',
                'tgl_lahir' => '2008-01-02',
                'tlp' => '6285817864951',
                'jk' => 'L',
                'address' => 'Kaliabang Bungur RT 004/018 Harapan Jaya Bekasi Utara , BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Habil Alkansyah',
                'nisn' => '0076149973',
                'tgl_lahir' => '2007-12-13',
                'tlp' => null,
                'jk' => 'L',
                'address' => 'Kaliabang Bungur RT 001/001 Pejuang Medan Satria , JATISAMPURNA, KOTA BEKASI, JAWA BARAT, 17131, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Haudhi Shofie',
                'nisn' => '0088063600',
                'tgl_lahir' => '2008-07-07',
                'tlp' => '62895602232507',
                'jk' => 'P',
                'address' => 'Kaliabang Bungur Al Bahar RT 005/018 Harapan Jaya Bekasi Utara , BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Intan Amelia',
                'nisn' => '0085353752',
                'tgl_lahir' => '2008-01-21',
                'tlp' => '6281284402552',
                'jk' => 'P',
                'address' => 'Jl Raya Seroja No 11 RT 002/028 Kel Harapan Jaya, Kota Bekasi , BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jihan Rohidattul Aisy',
                'nisn' => '0083950007',
                'tgl_lahir' => '2008-06-07',
                'tlp' => '6289638607634',
                'jk' => 'P',
                'address' => 'Pondok Ungu Rt 004/06 , MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17132, 17132',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaila Citra Hayatunnisa',
                'nisn' => '0088678956',
                'tgl_lahir' => '2008-05-07',
                'tlp' => null,
                'jk' => 'P',
                'address' => 'KP. UJUNG HARAPAN BAHAGIA, BABELAN, KABUPATEN BEKASI, JAWA BARAT, 17610',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kareem Ben Zemma',
                'nisn' => '0087419572',
                'tgl_lahir' => '2008-11-04',
                'tlp' => '6285811495929',
                'jk' => 'L',
                'address' => 'Kaliabang Bungur PLN RT 002/018 Harapan Jaya Bekasi Utara MARGAMULYA, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maya Syamsiah',
                'nisn' => '0084168012',
                'tgl_lahir' => '2008-05-15',
                'tlp' => '6289513626948',
                'jk' => 'P',
                'address' => 'JL. KALIABANG PENGARENGAN KALIABANG TENGAH, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17125, 17125',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Meisha Laura Idris',
                'nisn' => '0085817044',
                'tgl_lahir' => '2008-05-07',
                'tlp' => '6289613554445',
                'jk' => 'P',
                'address' => 'Kp. Pangkalan RT.002/008 SUKAMEKAR, SUKAWANGI, KABUPATEN BEKASI, JAWA BARAT, 17655, 17655',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Millatul Karimah',
                'nisn' => '3082066917',
                'tgl_lahir' => '2008-10-24',
                'tlp' => '6289601999968',
                'jk' => 'P',
                'address' => 'KALIABANG BUNGUR PEJUANG, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17131, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhammad Aditya Nugroho',
                'nisn' => '0083928207',
                'tgl_lahir' => '2008-03-11',
                'tlp' => '6283813894309',
                'jk' => 'L',
                'address' => 'Jl. Gelatik No 08, Harapan Jaya, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhammad Mahrus Maaly',
                'nisn' => '3071753341',
                'tgl_lahir' => '2007-11-06',
                'tlp' => null,
                'jk' => 'L',
                'address' => 'Jln. Moh Noh Noer Kp. Banyusuci LEUWIMEKAR, LEUWILIANG, KABUPATEN BOGOR, JAWA BARAT, 16640, 16640',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nauri El Zahra', //
                'nisn' => '0087486888',
                'tgl_lahir' => '2008-04-11',
                'tlp' => null,
                'jk' => 'P',
                'address' => 'KA. Bahagia RT 03/04 , JATISAMPURNA, KOTA BEKASI, JAWA BARAT, 17131, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nazwa Khadijah',
                'nisn' => '0076419796',
                'tgl_lahir' => '2007-11-13',
                'tlp' => '6285591484084',
                'jk' => 'P',
                'address' => 'Kaliabang Bungur, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nurlatifa Arsya Kamila', //
                'nisn' => '0088469532',
                'tgl_lahir' => '2008-08-24',
                'tlp' => null,
                'jk' => 'P',
                'address' => 'Kav Perwira jaya. Jln Kh Muchtar Thabrani 04/12 no 72 Bekasi Utara PERWIRA, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17122, 17122',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oriza Magani',
                'nisn' => '0089127691',
                'tgl_lahir' => '2008-04-10',
                'tlp' => '6288292103897',
                'jk' => 'P',
                'address' => 'Pondok Ungu, Medan Satria, KOTA BEKASI, JAWA BARAT, 17132',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Putra Ramadhan', //
                'nisn' => '0075844875',
                'tgl_lahir' => '2007-09-08',
                'tlp' => '6285811503530',
                'jk' => 'L',
                'address' => 'Jl. Raya Seroja Al Bahar RT 004/018 No. 5 Harapan Jaya Bekasi Utara HARAPANJAYA, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Putri Ramdahani',
                'nisn' => '0078541256',
                'tgl_lahir' => '2007-09-08',
                'tlp' => '6281389978846',
                'jk' => 'P',
                'address' => 'Jl. Raya Seroja Al Bahar, Harapan Jaya, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rafi Ahmad Eka Saputra', //
                'nisn' => '0074560044',
                'tgl_lahir' => '2007-10-23',
                'tlp' => '62895617084299',
                'jk' => 'L',
                'address' => 'Kav Mandiri RT 007/021 Kel Pejuang Kec Medan Satria,Kiota Bekasi , MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17131, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ratna Wati', //
                'nisn' => '3084789285',
                'tgl_lahir' => '2008-11-19',
                'tlp' => '628979947164',
                'jk' => 'P',
                'address' => 'Kaliabang Bungur RT 001/001 Pejuang Medan Satria PEJUANG, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17131, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rehan Bilal Rizqullah', //
                'nisn' => '0085398286',
                'tgl_lahir' => '2008-07-12',
                'tlp' => '6282211005883',
                'jk' => 'L',
                'address' => 'Kaliabang Bungur RT 001/001 Pejuang Medan Satria , BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Salsa Sabilah', //
                'nisn' => '0074440493',
                'tgl_lahir' => '2007-06-27',
                'tlp' => '6285811500370',
                'jk' => 'P',
                'address' => 'Kaliabang Bungur RT 004/018 Harapan Jaya Bekasi Utara HARAPANJAYA, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17124, 17124',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sufi M.Laila',
                'nisn' => '0071019283',
                'tgl_lahir' => '2007-12-12',
                'tlp' => '62895619906388',
                'jk' => 'P',
                'address' => 'Pondok Ungu, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17132',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Syarah Fahilatunnisa', //
                'nisn' => '0081760427',
                'tgl_lahir' => '2008-01-21',
                'tlp' => null,
                'jk' => 'P',
                'address' => 'jl sultan agung pondok ungu rt 04 rw07 kec medan Satria kel medan Satria kota bekasi MEDANSATRIA, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17132, 17132',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tsalitsa Adzka Muqita',
                'nisn' => '0087613558',
                'tgl_lahir' => '2008-03-25',
                'tlp' => '6281287079648',
                'jk' => 'P',
                'address' => 'KA. Ilir, MEDANSATRIA, KOTA BEKASI, JAWA BARAT, 17131',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tsuaibatul Aslamiyah',
                'nisn' => '0075820334',
                'tgl_lahir' => '2007-09-26',
                'tlp' => '6282210874357',
                'jk' => 'P',
                'address' => 'Kaliabang Tengah, BEKASI UTARA, KOTA BEKASI, JAWA BARAT, 17125',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yulia Rahma Ismi Rizkia',
                'nisn' => '0078087791',
                'tgl_lahir' => '2007-10-18',
                'tlp' => '6281286572291',
                'jk' => 'P',
                'address' => 'Jl. Kalimanggis No. 9, JATIASIH, KOTA BEKASI, JAWA BARAT, 17423',
                'class' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
